### ISSUE TITLE
4.19.2

### ISSUE THREAD

**Issue by emperor-katax** [Temaran/UE4ShaderPluginDemo#11]
Application is not working with 4.19.2 .... can you fix?

**Comment by Temaran** [comment]
Hello!

I've been thinking about updating this project for quite some time, since a LOT has happened in the engine since I did this.

I just haven't gotten around to it yet :)
I have two planned projects right now, hopefully I can get to this after those two.

It's always fun to hear there is interest though!

/Temaran

**Comment by emperor-katax** [comment]
... this is great when you follow your previous posts ... : ) ,, .. ,,  .. please if I can do some help, dont hesitate to ask ... here is my question in answer hub, good for start thou...  ... 
https://answers.unrealengine.com/questions/808195/shader-in-c-with-419.html

-- > thanks again ! ... : P ,,,,,,,

**Comment by emperor-katax** [comment]
.. dude, any update here thou ?

**Comment by Temaran** [comment]
Sorry, we are in crunch for our next release, I couldn't find any time to
look into it.

/Temaran

2018-07-19 3:48 GMT+02:00 Katax <notifications@github.com>:

**Comment by emperor-katax** [comment]
Thanks for the reply... : ) ,, 
.. ok, I will work on this, and if it works, I`ll share some updates with you .... 

Thanks again .. 
- Katax

**Comment by Temaran** [comment]
Cool!

Ill still try to have a look when / if I get some time over

**Comment by keithlostracco** [comment]
I'm really interested in this project as well. I'm new to EU but have quite a bit of experience with writing shaders, it would be great to get this working in UE4.2 for some to implement some custom stuff!

**Comment by freeplanet** [comment]
It seems a very interesting plugin.
Please any chance to make this works on UE 4.20?
Thanks!

**Comment by Umax1004** [comment]
Hey I sent a pull request and updated the plugin to UE 4.20 have a look at it and let me know if it works properly. If it doesn't then I'll try to fix it. @freeplanet @keithlostracco @Temaran @emperor-katax

**Comment by Temaran** [comment]
Very cool Umax!
I merged your pull request, unfortunately we are now in crunch for CES, so I still haven't found any time to upgrade the project :(

So thank you Umax for taking some time and getting it to 4.20!

/Temaran
