### ISSUE TITLE
Issue accessing shader files in UE 4.21

### ISSUE THREAD

**Issue by MaximeDup** [Temaran/UE4ShaderPluginDemo#13]
Moving my project from 4.20 to 4.21 while using this plugin i now face an issue for accessing my shader files:

![shaderaccess](https://user-images.githubusercontent.com/8050632/49835879-eac25880-fda0-11e8-978d-2a1e739a6dcc.jpg)

**Comment by etiennepinchon** [comment]
Same :'(

**Comment by MaximeDup** [comment]
Solved it. You need to add root 'shader' folder back as default path for storing shaders. Explained it all there: 
https://forums.unrealengine.com/development-discussion/rendering/1562454-virtual-shader-source-path-link-custom-shaders-4-21
