### ISSUE TITLE
It will crash when run develop when another pc git clone this demo

### ISSUE THREAD

**Issue by wjingzhe** [Temaran/UE4ShaderPluginDemo#5]
Hello,
I'm sure that I cooked completed and successed.
But when run it, somehing image happened.I used to rewrite it in a new project and found that I loss the stars cycles.

![qq 20161011170925](https://cloud.githubusercontent.com/assets/7407101/19264986/c8487b26-8fd5-11e6-9377-062c753198e7.png)

**Comment by Temaran** [comment]
Hello there!

I understand you are having some kind of problem, but without a reproduction case or a more detailed description of the problem, I'm not sure what I can do.

/Temaran

**Comment by wjingzhe** [comment]
> Hello there!
> 
> I understand you are having some kind of problem, but without a reproduction case or a more detailed description of the problem, I'm not sure what I can do.
> 
> /Temaran

I'm so sorry.maybe just some version problem.(Because en is not my first language,most time I forget to read all the notifies,and I give up to this codes...)
