### ISSUE TITLE
How to set this shader to custom surface in blueprint project only?

### ISSUE THREAD

**Issue by AngelTs** [Temaran/UE4ShaderPluginDemo#6]
From your tutorial it is no clear about that

**Comment by Temaran** [comment]
Hello there!

As you need to invoke the RHI interface (low level rendering functions) of
the engine, I'm afraid you cannot use this in a pure blueprint project.
You could compile the plugin and package it as an "installed" plugin, which
you could then use in a BP only project, but you would still have to do the
build and package in a source build.

Best regards,
Temaran

2017-04-17 9:35 GMT+02:00 AngelTsTsvetkov <notifications@github.com>:
